### PR TITLE
⬆️ Upgrades Plex Media Server to 1.32.4.7195

### PR DESCRIPTION
**Pull request by bertybuttface**
# Proposed Changes

Upgrade Plex to latest public release

## Related Issues

None

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @bertybuttface 👍 

../Frenck

**Comment by bertybuttface** [comment]
Any time, is it worth automating this?

**Comment by frenck** [comment]
I haven't found a way for renovate to grab the version reliably, if you can, feel free to submit a PR that does.

**Comment by bertybuttface** [comment]
# Automatic Plex Version Update

To automatically update the URL for the latest version of Plex in your Dockerfile, you can follow these steps:

1. Create `latest_version.sh`

```bash
#!/bin/bash
LATEST_VERSION=$(curl -s "https://api.github.com/repos/plexinc/plex-media-server/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
echo $LATEST_VERSION
```

2. Modify Dockerfile to use the `latest_version.sh` script and dynamically set the version during the build process.

```Dockerfile
FROM some_base_image

# Copy the latest_version.sh script into the container
COPY latest_version.sh /usr/local/bin/

# Run the latest_version.sh script and capture the output into an ARG
ARG PLEX_VERSION=$(latest_version.sh)

# Download and install the specified version of Plex
RUN curl -o plex.deb "https://downloads.plex.tv/plex-media-server/${PLEX_VERSION}/plex-media-server-${PLEX_VERSION}.deb" \
   && dpkg -i plex.deb \
   && rm plex.deb

# Other Dockerfile instructions...
```

3. Create a GitHub Actions workflow that runs the script and commits the Dockerfile changes whenever a new release of Plex is available. This workflow can be triggered periodically or when specific events occur, such as a new release in the Plex repository.

Here's an example workflow file (e.g., `.github/workflows/update-plex.yml`):

```yaml
name: Update Plex Version

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-plex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Plex Version
        run: |
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/plexinc/plex-media-server/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
          sed -i "s/ARG PLEX_VERSION=.*/ARG PLEX_VERSION=$LATEST_VERSION/" Dockerfile
      
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Update Plex version to $LATEST_VERSION" --author="GitHub Actions <actions@github.com>"
          git push
```

In this workflow, the `update-plex` job uses the `checkout` action to fetch the repository's contents. It then runs the script to retrieve the latest version and uses `sed` to replace the value of `PLEX_VERSION` in the Dockerfile. Finally, it commits the changes with a message indicating the updated version and pushes them back to the repository.

**Comment by bertybuttface** [comment]
Renovate is a better solution I'd not seen that as we posted at the same time.

This was a quick example to ask if this was the right way forward and it clearly isn't. Yes I did use AI help but only as this was a toy example to ask for clarity, I would of course not commit AI generated code to the repo.

**Comment by frenck** [comment]
Please don't waste my time with that crap. For reference, see also:

https://www.home-assistant.io/blog/2023/01/23/help-others-leave-ai-at-the-dor/

**Comment by bertybuttface** [comment]
Very well,I shan't waste my time with this crap either, good luck with the rest of the day.

**Comment by frenck** [comment]
Have a good day as well 👍 🍻

**Pull request merged**
