### PR TITLE
Add icon (sidebar)

### PR DESCRIPTION
**Pull request by gordio**
# Proposed Changes

Just added icon.

### CODE REVIEW

**Comment by frenck** [comment]
Cool! How does it look?

**Comment by gordio** [comment]
I'm expecting it to be like that
image

**but** don't know how to test it locally :)

**Comment by frenck** [comment]
> I'm expecting it to be like tha

It doesn't....

> but don't know how to test it locally :)

Hence me asking, as this PR will never work :)
This add-on has no Ingress support.

Please... **ALWAYS** test your PR for opening one. Not just for this project, but this applies to ANY open source project you are contributing to.

**Comment by gordio** [comment]
> Please... ALWAYS test your PR for opening one. Not just for this project, but this applies to ANY open source project you are contributing to.

Oh. "Thank you".

_We can move that discussion further. (P.S. I'm just try to improve what I'd like. But don't know how to test it, judge me for that…)_

_It's you responsibility to verify all P.R.'s (sorry), even if you super duper trust that contributor. 'coz it's YOU "HOST". When you create open source project it's YOU responsibility to support it. Right?_
_Or transfer access to community._

**Comment by frenck** [comment]
>  When you create open source project it's YOU responsibility to support it. Right?

Sure, absolutely right, I test everything before putting it out.

However, your little stunt here wasted some of my time today, which I could have spent on other open-source things. My comments were meant as an eye-opener against your actions towards an open source project.

../Frenck

**Comment by gordio** [comment]
Thx for reply. Sorry, I took previous message (more) aggressive that it's `expected` to be. 
Have productive day ;)

**Pull request closed without merging**
