### PR TITLE
⬆️ Upgrades Plex Media Server to 1.41.2.9200

### PR DESCRIPTION
**Pull request by TomK**
# Proposed Changes

Plex Server updates since https://forums.plex.tv/t/plex-media-server/30447/646

## Summary by CodeRabbit

- **New Features**
	- Updated to the latest version of Plex Media Server (1.41.2.9200).
  
- **Bug Fixes**
	- Improved the installation process by using the updated download URL for the Plex Media Server package.

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Nice! Thanks, @TomK 👍 

../Frenck

**Comment by hashamori** [comment]
Thank you for the update.

Since I got to 1.41.2.9200, I received a notification about a newer version 1.41.3.9292... 
image


Is there any schedule to launch the update to HA Addon?

**Comment by frenck** [comment]
> Since I got to 1.41.2.9200, I received a notification about a newer version 1.41.3.9292...

Cool, but that is a bit of an odd comment to have on this PR, as your comment has nothing to do with the review 😄 

> Is there any schedule to launch the update to HA Addon?

No, there is not; but feel free to open a pull request to contribute an update. ❤️ 

../Frenck

**Comment by TomK** [comment]
@hashamori yes, i was frustrated by that. It seems they brought this new version out of beta at the same time i put this PR in 🤦

**Pull request merged**
