### PR TITLE
Support to mount external CIFS disk

### PR DESCRIPTION
**Pull request by dianlight**
# Proposed Changes

Simple startup end config mod to allow, only if protection mode is disable, to mount network share on startup. 

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
This should not be a concern to the add-on.
I've rejected this suggestion in the past, and will now do it again.

Besides, this is not enough to make this work. Disabling project mode won't work, as this add-on doesn't request any of that. The button simply will be hidden in the latest Supervisor release.

Nevertheless, thank you for your contribution.

**Comment by dianlight** [comment]
I apologize for my ignorance but apart from that on the current version (105) it works.  (I've been using it on an rpi4 for more than a month) the only way to use the mount seems to be to remove the protection mode.  that you know in the next versions of the supervisor is there a specific permit?

L

**Comment by frenck** [comment]
`105` is not current. `200` is current.

**Comment by dianlight** [comment]
You are right.
I’m on Supervisor 200 HassOS 3.10

**Comment by frenck** [comment]
image

No protection switch (fresh install).

**Comment by frenck** [comment]
We can add in tons of these kinds of features on add-on level, in the end, I'll end up adding them to almost every add-on I distribute.

This should all be handled by the OS in my opinion, not the container. I don't want to end up in dependency and maintenance hell (besides, it doesn't make the configuration for newer users any friendlier).

I hope, someday, we'll get mounting options to Home Assistant itself, to add hard disks or network drives even.

**Comment by dianlight** [comment]
You are right until in config.json you add the protection mode and SYS_ADMIN privilege 

plex/config.json Line 25 on my pull request.

I look in the ha code and don’t seem dependent on a fresh install or upgrade.

I will tray a fresh install to check...

**Comment by frenck** [comment]
aah right, missed that one in your PR. Sorry about that.

Nevertheless, my answer stays the same.

**Comment by dianlight** [comment]
You are right.
I’m working on a patch for ha os but is quite hard because need a cross modify on all the stack. This was a simplier workaround to use external disks. I have also a samba mod addon (dianlight/sambanas) that mount by label external disks so other addons can mount via internal network. 

in any case, thanks anyway.  as I wrote initially I understand the reason for the refusal.

**Pull request closed without merging**
